---
apiVersion: v1
kind: Service
metadata:
  name: projects-service-service
spec:
  type: NodePort
  selector:
    service: projects-service
    tier: backend
  ports:
    - name: http
      protocol: TCP
      port: 50001
      targetPort: http
